### ISSUE TITLE
Source AquaWrench.exe

### ISSUE THREAD

**Issue by vineetkia** [FuzzySecurity/IBM-RedCON-2020#1]
It would be great if we could work out this for windows 2004 build and load unsigned driver into the kernel.

**Comment by FuzzySecurity** [comment]
For science huh, sounds like a good reason? :fire:

![](https://media3.giphy.com/media/RgtzrqxF7U5IYLzaxl/giphy.gif)

Sorry but no :wink:. 2004 support can be added with 1-2 hours of work, it's not very difficult but has not yet been included.
